### ISSUE TITLE
Evaluate NNI by GP Criterion

### ISSUE THREAD

**Issue by davidrich27** [phylovi/bito#372]
- Given a proposed NNI to add to the sDAG, determine whether we would like to add NNI based on the GP Criterion.
- This should be performed without actually using SubsplitDAG::AddNodePair() (avoid directly mmodifying the DAG).

**Comment by matsen** [comment]
Some steps:

1. Modify code so that we have some "extra" plvs and gpcsps to work with. Do this by increasing the count of things passed to the GPEngine constructor. Make sure that this doesn't change existing functionality. 
2. Set up a test in which we have two DAGs, `pre_nni` (here called A) and `post_nni` (here called B), each of which are constructed via lists of trees stored in the repo. B is the same as A except that it has an additional edge and two new nodes. Assume that all edges for these DAGs are 0.1, and don't optimize them. Record the per-edge marginal likelihood for  the additional edge in B, and the goal is to replicate that with additional code taking the NNI and the A DAG. 

We should implement this via a new method (alongside [this one](https://github.com/phylovi/bito/blob/main/src/gp_dag.hpp#L56)) that takes in an NNI and spits out an operation vector. 

Ideally this should be set up so that the new nni is the last tree in the file for the `post_nni` dag, in which case 🤞 we should be able to "read off" the new operations at the end of the `post_nni` marginal likelihood computation Operation vector.
